name: Build image
on:
  workflow_call:
    inputs:
      image:
        description: "Full image reference, including hash"
        required: true
        type: string
      tag:
        description: "New Image tag"
        required: true
        type: string
      REGISTRY:
        description: "The registry of the"
        required: false
        type: string
        default: "ghcr.io"
      REGISTRY_USER:
        description: "The username to use for the registry"
        required: false
        type: string
        default: "${{ github.actor }}"
    secrets:
      REGISTRY_TOKEN:
        description: "The token to use for the registry"
        required: true

jobs:
  retag-image:
    runs-on: ubuntu-latest

    steps:
      - name: Install Crane
        uses: imjasonh/setup-crane@31b88efe9de28ae0ffa220711af4b60be9435f6e # v0.4

      - name: Tag image
        shell: bash
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | crane auth login ${{ inputs.REGISTRY }} --username ${{ inputs.REGISTRY_USER }} --password-stdin
          crane tag ${{ inputs.image }} ${{ inputs.tag }}
